name: Java CI with Maven

on:
  push:
    branches:
      - main
  workflow_dispatch:



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build Maven project
      run: mvn package

    - name: Increase patch version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        NEW_VERSION=$(echo $VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
        mvn versions:set -DnewVersion=$NEW_VERSION
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build -t ${{ vars.DOCKER_USER }}/jarimage:${{ env.NEW_VERSION }} .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ vars.DOCKER_USER }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
            
    - name: Push to DockerHub
      run: docker push  ${{ vars.DOCKER_USER }}/jarimage:${{ env.NEW_VERSION }}
