name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.VERSION'
  pull_request:
      branches: [ "master" ]
      paths-ignore:
        - '.VERSION'



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build Maven project
      run: mvn package

    - name: Increase patch version
      run: |
        base_version=$(cat .VERSION)
        NEW_VERSION=$(echo $base_version | awk -F. '{$NF = $NF + 1} 1' | sed 's/ /./g')
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build -t ${{ vars.DOCKER_USER }}/jarimage:${{ env.NEW_VERSION }} -t ${{ vars.DOCKER_USER }}/jarimage:latest .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ vars.DOCKER_USER }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
            
    - name: Push to DockerHub
      run: docker push ${{ vars.DOCKER_USER }}/jarimage:${{ env.NEW_VERSION }} ${{ vars.DOCKER_USER }}/jarimage:latest

    - name: Update version
      run: |
        # Config git identity
        git config --local user.email "github-actions"
        git config --local user.name "github-actions"

        echo "The new version is ${{ env.NEW_VERSION }}"
        
        echo "${{ env.NEW_VERSION }}" > .VERSION
        git add .VERSION
        git commit -m "Update .VERSION"
        git push

