name: Java CI with Maven

on:
  push:
    branches:
      - main
  workflow_dispatch:



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Maven Release
      uses: qcastel/github-actions-maven-release@v1
      with:
        release-bot-name: 'release-bot'
        release-bot-email: 'release-bot@example.com'
        gpg-enabled: false
